FROM ghcr.io/home-assistant/home-assistant:2026.9.4

ENV UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

WORKDIR /usr/src/homeassistant

RUN pip3 install --no-cache-dir debugpy

EXPOSE 5678

ENTRYPOINT ["python3", "-m", "homeassistant", "--config", "/config"]